### ISSUE TITLE
Question: What's the advanced version?

### ISSUE THREAD

**Issue by 3noch** [Gabriel439/Haskell-Managed-Library#2]
From the README:
> Also, the Managed monad has a less intimidating name so I feel more comfortable using it to teach beginners.

I'm essentially a beginner, but I've used much more complicated monads for resource management than this one. I didn't like using them. What are the options out there for resource management and what are the trade-offs to using this simpler one?

**Comment by Gabriel439** [comment]
There are two common alternatives:

* `Acquire` from `resourcet`: http://hackage.haskell.org/package/resourcet-1.1.2.3/docs/Data-Acquire.html

The advantage of  of `Acquire` is that it preserves the open and close action, which can be handy for integrating resource management with coroutine libraries (like `pipes` and `conduit`).  The disadvantage compared to `Managed` is that if you have something only in continuation-passing style you can no longer wrap it in `Acquire` (because you don't have access to the original open/close actions).

* `ContT`/`Codensity` (from `transformers` and `kan-extensions`, respectively).

These generalize `Managed` by working over an arbitrary base monad.  The disadvantage is that the names are not very helpful.

Those are not the only monads for managing resources (there's also things like regions for additional safety), but those were the ones I had in mind when writing that sentence in the documentation.

**Comment by 3noch** [comment]
Thanks, that's very helpful. The one I used was `MonadBaseControl` (using the `resource-pool` package). It was a real pain to derive an instance for my very simple monad (based on `StateT`). I was also working with a colleague who didn't yet know Haskell. It was a very intimidating foray into Haskell for him. What would you suggest? It seems that libraries settle on various choices for this problem, but integrating them seems like it would be quite painful.

**Comment by Gabriel439** [comment]
Actually, Haskell is great for integrating things once you realize that you don't need to standardize on anything.  I recommend you read [this post](http://www.haskellforall.com/2012/09/the-functor-design-pattern.html) and the [mmorph tutorial](http://hackage.haskell.org/package/mmorph-1.0.4/docs/Control-Monad-Morph.html#g:3), which show you can do integration for incompatible monads.

More generally, in Haskell the way you integrate things is to define conversion functions to unify them to agree on a common type.

**Comment by 3noch** [comment]
Couldn't have asked for a better response. Thank you

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by Gabriel439** [comment]
I'll go ahead and close this since I think the question was resolved
