### ISSUE TITLE
Mention dangers of `with`

### ISSUE THREAD

**Issue by andrewthad** [Gabriel439/Haskell-Managed-Library#8]
Most users of this library probably understand this almost, but I think it's worth mentioning that when using `with`, the user takes on the burden of ensuring that the returned value doesn't cause the resource to escape.

**Comment by Gabriel439** [comment]
I can upload this to Hackage if you don't have any other pending requests

**Comment by andrewthad** [comment]
Thanks. The documentation you added is very clear.

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by mitchellwrosen** [comment]
Along these lines, would it make sense to add an instance for [`MonadUnliftIO`](https://hackage.haskell.org/package/unliftio-core-0.1.0.0/docs/Control-Monad-IO-Unlift.html)?

```haskell
instance MonadUnliftIO Managed where
  askUnliftIO = Managed (\k -> k (UnliftIO (>>- return)))
```

The types work out, but when you unlift, you are clearly "ending" the built-up callbacks, then re-entering `Managed`.

**Comment by Gabriel439** [comment]
@mitchellwrosen: I'm not a big of classes like `MonadUnliftIO` because they have no mathematical laws associated with them.  This is especially pertinent here since (as you point out) the implementation that type-checks is not necessarily desirable behavior.  It's basically equivalent to `with return` which allows access to the resource after all finalizers have been called
